
joysticks = {
    'xbox_controller' : {
        'AXIS_LEFT_X': 0,
        'AXIS_LEFT_Y': 1,
        'AXIS_LEFT_TRIGGER': 2,
        'AXIS_RIGHT_TRIGGER': 3,
        'AXIS_RIGHT_X': 4,
        'AXIS_RIGHT_Y': 5,

        'POV_UP': 0,
        'POV_UP_RIGHT': 45,
        'POV_RIGHT': 90,
        'POV_DOWN_RIGHT': 135,
        'POV_DOWN': 180,
        'POV_DOWN_LEFT': 225,
        'POV_LEFT': 270,
        'POV_UP_LEFT': 315,

        'A_BUTTON': 1,
        'B_BUTTON': 2,
        'X_BUTTON': 3,
        'Y_BUTTON': 4,
        'LB_BUTTON': 5,
        'RB_BUTTON': 6,
        'SELECT_BUTTON': 7,
        'START_BUTTON': 8,
        'L3_BUTTON': 9,
        'R3_BUTTON': 10,
    },
    'playstation_dualsense_controller' : {
        'AXIS_LEFT_TRIGGER': 2,
        'AXIS_RIGHT_TRIGGER': 5,

        'AXIS_LEFT_X': 0,
        'AXIS_LEFT_Y': 1,

        'POV_UP': 0,
        'POV_UP_RIGHT': 45,
        'POV_RIGHT': 90,
        'POV_DOWN_RIGHT': 135,
        'POV_DOWN': 180,
        'POV_DOWN_LEFT': 225,
        'POV_LEFT': 270,
        'POV_UP_LEFT': 315,

        'A_BUTTON': 1,
        'B_BUTTON': 2,
        'X_BUTTON': 3,
        'Y_BUTTON': 4,
        'LB_BUTTON': 5,
        'RB_BUTTON': 6,
        'SELECT_BUTTON': 7,
        'START_BUTTON': 8,
        'L3_BUTTON': 9,
        'R3_BUTTON': 10,
    },
    'playstation_dualshock_4' : {
        'AXIS_LEFT_TRIGGER': 3,
        'AXIS_RIGHT_TRIGGER': 4,

        'AXIS_RIGHT_X': 2,
        'AXIS_RIGHT_Y': 5,

        'AXIS_LEFT_X': 0,
        'AXIS_LEFT_Y': 1,

        'POV_UP': 0,
        'POV_UP_RIGHT': 45,
        'POV_RIGHT': 90,
        'POV_DOWN_RIGHT': 135,
        'POV_DOWN': 180,
        'POV_DOWN_LEFT': 225,
        'POV_LEFT': 270,
        'POV_UP_LEFT': 315,

        'A_BUTTON': 2,
        'B_BUTTON': 3,
        'X_BUTTON': 1,
        'Y_BUTTON': 4,
        'LB_BUTTON': 5,
        'RB_BUTTON': 6,
        'SELECT_BUTTON': 9,
        'START_BUTTON': 10,
        'L3_BUTTON': 11,
        'R3_BUTTON': 12,
    }
}
